version: "3.9"

services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - WATCHPACK_POLLING=true
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src
    ports:
      - "8000:8000"
      - "3000:3000"
