version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: dockerfile
    image: cs50web-capstone-django
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src
    ports:
      - "8000:8000"

  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer.Dockerfile
    image: cs50web-capstone-devcontainer
    container_name: devcontainer
    volumes:
      - .:/usr/src
    tty: true
    stdin_open: true
