# Generated by Django 4.1.4 on 2023-01-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_answer',
            field=models.TextField(null=True),
        ),
    ]
