# Generated by Django 4.1.4 on 2023-02-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_submission_submitted_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='correct_answer',
            field=models.CharField(max_length=50),
        ),
    ]
